### ISSUE TITLE
可以考虑，Indicator完全用java写

### ISSUE THREAD

**Issue by tanweijiu** [hejunlin2013/SuperIndicator#1]
这样用布局会不会不太好移植？

**Comment by smartyuge** [comment]
嗯，是的，还须要完善。3q

**Comment by hackware1993** [comment]
@hejunlin2013 那个原点指示器，可以试试 https://github.com/hackware1993/MagicIndicator

**Comment by smartyuge** [comment]
@hackware1993 原点指示器已经有考虑下一步拓展的思路了。谢谢建议。我试了下你的indicator，在你的activity_main里的scrollview中包的linearlayout加入如下一段代码 <TextView
                android:layout_marginTop="180dp"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:text="3453453453453"/>测试时，发现上下滑动和左右滑动有冲突，建议多试几个场景，如srollview中嵌套listview，gridevice, recycleview

**Comment by hackware1993** [comment]
@hejunlin2013 没有冲突啊
