### ISSUE TITLE
导入报错

### ISSUE THREAD

**Issue by CCC2016** [hejunlin2013/SuperIndicator#5]
Error:Execution failed for task ':app:processDebugManifest'.

> Manifest merger failed with multiple errors, see logs

导入包时报此错误。

[CSDN](http://blog.csdn.net/codezjx/article/details/38669939)

**Comment by smartyuge** [comment]
@CCC2016 改下gradle版本及build版本吧，可以直接去stackoverflow上看解决方案，和类库联系不大。
